const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium, request } = require('playwright');
const base = process.env.CHAPITOUR_TEST_URL || 'http://127.0.0.1:8791/pruebas/chapitour-premia/';
const output = process.env.CHAPITOUR_QA_DIR || '/private/tmp/chapitour-premia-qa';
fs.mkdirSync(output, { recursive: true });

(async () => {
  const client = await request.newContext();
  let state = await (await client.get(`${base}api.php`)).json();
  const csrf = state.csrf;
  const post = async (action, data = {}, expected = 200) => {
    const response = await client.post(`${base}api.php`, { headers: { 'X-CSRF-Token': csrf }, data: { action, ...data } });
    const result = await response.json();
    assert.equal(response.status(), expected, `${action}: ${JSON.stringify(result)}`);
    if (expected === 200) state = result;
    return result;
  };
  assert.equal(state.user, null);
  assert.equal(state.codes.length, 0);
  assert.equal(state.campaign.enabled, false);
  assert.equal(state.campaign.visits_per_reward, null);
  assert.equal((await client.post(`${base}api.php`, { data: { action: 'demo_login', role: 'admin' } })).status(), 403);
  assert.equal((await client.get(`${base}api.php?action=redeem`)).status(), 405);
  await post('save_business', {}, 403);
  await post('demo_login', { role: 'client' });
  assert.equal(state.user.name, 'Dani');
  assert.equal(state.codes.length, 3);
  assert.equal(state.promotions.length, 4);
  await post('save_promotion', {}, 403);
  const activeClientCode = state.codes.find(c => c.status === 'Activo');
  await post('redeem', { code: activeClientCode.code, confirm: activeClientCode.code }, 403);
  await post('whatsapp', { code: activeClientCode.code }, 422);
  const grant = await post('prepare_spin');
  const token = grant.spin_token;
  await post('spin', { token: 'invalid' }, 409);
  const spin1 = await post('spin', { token });
  assert(!['pictogramas', 'jimar'].includes(spin1.prize.business_id));
  assert.equal(spin1.prize.expires_at - spin1.prize.created_at, 72 * 3600);
  assert.match(spin1.prize.code, /^DEMO-CHAPI-/);
  const spin2 = await post('spin', { token });
  assert.equal(spin1.prize.code, spin2.prize.code, 'Retrying a spin must not create a second prize');
  assert.equal(spin1.codes.length, spin2.codes.length);
  const beforeReload = state.codes.length;
  await post('state');
  assert.equal(state.codes.length, beforeReload);
  await post('demo_login', { role: 'admin' });
  assert.equal(state.promotions.filter(p => p.publication === 'draft').length, 2);
  const anotherBusinessCode = state.codes.find(c => c.business_id === 'garage' && c.status === 'Activo');
  const expired = state.codes.find(c => c.status === 'Vencido');
  await post('redeem', { code: expired.code, confirm: expired.code }, 409);
  await post('demo_login', { role: 'ally', business_id: 'street' });
  assert(state.codes.every(c => c.business_id === 'street'));
  assert(state.promotions.every(p => p.business_id === 'street'));
  assert.equal(state.businesses.length, 1);
  await post('redeem', { code: anotherBusinessCode.code, confirm: anotherBusinessCode.code }, 404);
  await post('delete_promotion', { id: 'promo-street', confirm: 'promo-street' }, 403);
  await post('save_business', {}, 403);
  await post('save_promotion', {}, 403);
  await post('redeem', { code: activeClientCode.code, confirm: 'wrong' }, 422);
  await post('redeem', { code: activeClientCode.code, confirm: activeClientCode.code });
  assert.equal(state.codes.find(c => c.code === activeClientCode.code).status, 'Redimido');
  await post('redeem', { code: activeClientCode.code, confirm: activeClientCode.code }, 409);
  await post('change_status', { code: activeClientCode.code, status: 'Activo' }, 404);
  console.log('PASS role isolation, CSRF, 72-hour expiry, single redemption, idempotent spin, draft exclusion');

  await post('demo_login', { role: 'admin' });
  const provisional = state.promotions.find(p => p.id === 'promo-pictogramas');
  await post('save_promotion', { ...provisional, publication: 'reference', whatsapp: '' }, 422);
  await post('save_promotion', { ...provisional, publication: 'approved', whatsapp: '', confirmed: true }, 422);
  await post('save_promotion', { ...provisional, description: '10 % de descuento al comprar una bebida de café y un postre.', whatsapp: '', publication: 'draft' });
  assert.equal(state.promotions.find(p => p.id === provisional.id).publication, 'draft');
  await post('save_business', { name: 'Aliado de prueba QA', email: 'aliado-qa@example.invalid', password: 'testing-only-123' });
  const newBusiness = state.businesses.find(b => b.name === 'Aliado de prueba QA');
  await post('save_promotion', { business_id: newBusiness.id, description: 'Borrador para validar formulario, sin beneficio aprobado.', publication: 'draft', whatsapp: '', included: '', hours: '', restrictions: '' });
  const newPromotion = state.promotions.find(p => p.business_id === newBusiness.id);
  await post('delete_promotion', { id: newPromotion.id, confirm: 'wrong' }, 422);
  await post('delete_promotion', { id: newPromotion.id, confirm: newPromotion.id });
  assert(!state.promotions.some(p => p.id === newPromotion.id));
  await post('logout');
  await post('login', { email: 'aliado-qa@example.invalid', password: 'testing-only-123' });
  assert.equal(state.user.role, 'ally');
  assert.equal(state.businesses[0].id, newBusiness.id);
  assert.equal(state.codes.length, 0);
  await post('demo_login', { role: 'admin' });
  await post('delete_business', { id: newBusiness.id, confirm: newBusiness.id });
  await post('logout');
  await post('login', { email: 'aliado-qa@example.invalid', password: 'testing-only-123' }, 401);
  await post('register', { name: 'Cliente QA', email: 'cliente-qa@example.invalid', password: 'testing-only-456', city: 'Bogotá' });
  assert.equal(state.codes.length, 0, 'A newly registered account must not inherit demo prizes');
  await post('prepare_spin', {}, 422);
  const userId = state.user.id;
  await post('profile', { name: 'Cliente actualizado', email: 'cliente-qa@example.invalid', city: 'Bogotá D.C.' });
  assert.equal(state.user.name, 'Cliente actualizado');
  await post('logout');
  await post('login', { email: 'cliente-qa@example.invalid', password: 'testing-only-456' });
  assert.equal(state.user.id, userId);
  await post('delete_account', { confirm: 'wrong' }, 422);
  await post('delete_account', { confirm: userId });
  assert.equal(state.user, null);
  await post('login', { email: 'cliente-qa@example.invalid', password: 'testing-only-456' }, 401);
  const isolated = await request.newContext();
  const fresh = await (await isolated.get(`${base}api.php`)).json();
  assert.equal(fresh.user, null);
  assert.equal(fresh.businesses.length, 6);
  await isolated.dispose();
  await client.dispose();
  console.log('PASS admin CRUD, draft approval validation, account lifecycle, empty new account, session isolation');

  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
    await context.addInitScript(() => { Object.defineProperty(navigator, 'share', { value: async () => {} }); });
    const page = await context.newPage();
    const errors = [], missing = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') { errors.push(m.text()); console.log('BROWSER ERROR',m.text()); } });
    page.on('response', r => { if (r.status() >= 400 && !r.url().includes('api.php')) missing.push(`${r.status()} ${r.url()}`); });
    const capture = async name => { await page.screenshot({ path: `${output}/${name}.png`, fullPage: !await page.locator('dialog').evaluate(el => el.open) }); };
    const overflow = async name => assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `Overflow: ${name}`);
    await page.goto(base);
    await page.getByRole('button', { name: /Crear mi cuenta/ }).waitFor();
    await page.evaluate(() => Promise.all(Array.from(document.images).map(i => i.decode().catch(() => {}))));
    await capture('inicio-desktop');
    const switchRole = async role => { await page.getByRole('button', { name: /Cambiar de vista/ }).click(); await page.locator(`[data-action="demo-${role}"]`).click(); await page.waitForFunction(() => !document.querySelector('dialog').open); };
    await switchRole('client');
    await page.getByRole('heading', { name: /Mis retos del mes/ }).waitFor();
    assert.equal(await page.getByRole('button', { name: /Crear mi cuenta/ }).count(), 0);
    const returnCard = await page.locator('.return-card').innerText();
    assert(!/6\/10|Ingresar código|cada 10|cada 8/.test(returnCard));
    const codeBeforeShare = await page.locator('.challenge.purple .progress-label').innerText();
    await page.locator('[data-action="share"]').click();
    assert.equal(await page.locator('.challenge.purple .progress-label').innerText(), codeBeforeShare);
    await capture('cliente-desktop');
    await page.goto(`${base}#inicio`);
    await page.locator('[data-action="preview-wheel"]').click();
    await page.locator('#wheel-disc').waitFor();
    await capture('ruleta-desktop');
    await page.locator('[data-action="spin"]').click();
    await page.getByRole('heading', { name: '¡Te ganaste una promoción especial!' }).waitFor();
    assert.equal(await page.locator('dialog [data-action="whatsapp"]').isDisabled(), true);
    await capture('premio-desktop');
    await page.keyboard.press('Escape');
    await switchRole('ally');
    assert.equal(await page.getByRole('button', { name: /Crear promoción/ }).count(), 0);
    await page.getByRole('heading', { name: 'Panel del aliado' }).waitFor();
    await page.locator('#status-filter').selectOption('Redimido');
    assert.equal(await page.locator('[data-action="confirm-redeem"]').count(), 0);
    await page.locator('#status-filter').selectOption('');
    await page.locator('#code-search').fill('NO-EXISTE');
    await page.getByText('No hay códigos que coincidan con tu búsqueda.').waitFor();
    await page.locator('#code-search').fill('');
    await capture('aliado-desktop');
    const activeActions = await page.locator('[data-action="confirm-redeem"]').count();
    await page.locator('[data-action="confirm-redeem"]').first().click();
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
    assert.equal(await page.locator('[data-action="confirm-redeem"]').count(), activeActions);
    await page.locator('[data-action="confirm-redeem"]').first().click();
    await page.getByRole('button', { name: 'Confirmar redención', exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('dialog').open);
    assert.equal(await page.locator('[data-action="confirm-redeem"]').count(), activeActions - 1);
    await switchRole('admin');
    await page.locator('[data-action="pending"]').click();
    await page.waitForTimeout(100);
    assert.equal(await page.locator('.promotion-table tbody tr').count(), 2);
    await page.locator('#publication-filter').selectOption('');
    await capture('admin-desktop');
    await page.locator('[data-action="edit-promotion"][data-id="promo-pictogramas"]').click();
    assert.equal(await page.locator('dialog select[name="publication"]').inputValue(), 'draft');
    await page.keyboard.press('Escape');
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ['promociones', 'codigos', 'aliados']) {
      await page.goto(`${base}#${route}`);
      await page.waitForTimeout(80);
      await overflow(route);
      await capture(`admin-${route}-mobile`);
    }
    await switchRole('client');
    await overflow('client');
    await capture('cliente-mobile');
    await page.goto(`${base}#inicio`);
    await overflow('public');
    await capture('inicio-mobile');
    await page.locator('[data-action="preview-wheel"]').click();
    await page.locator('#wheel-disc').waitFor();
    await capture('ruleta-mobile');
    await page.locator('[data-action="spin"]').click();
    await page.getByRole('heading', { name: '¡Te ganaste una promoción especial!' }).waitFor();
    assert(await page.locator('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
    await capture('premio-mobile');
    await page.keyboard.press('Escape');
    await switchRole('ally');
    await overflow('ally');
    await capture('aliado-mobile');
    await page.locator('[data-action="logout"]').click();
    await page.getByRole('button', { name: 'Crear mi cuenta', exact: true }).click();
    await page.locator('dialog input[name="name"]').fill('Cuenta nueva QA');
    await page.locator('dialog input[name="email"]').fill('nueva-ui@example.invalid');
    await page.locator('dialog input[name="password"]').fill('new-test-123');
    await page.locator('dialog [type="submit"]').click();
    await page.getByText('Aquí aparecerán las promociones que ganes.').waitFor();
    await page.goto(`${base}#perfil`);
    await page.locator('main input[name="name"]').fill('Nuevo nombre QA');
    await page.getByRole('button', { name: 'Guardar cambios' }).click();
    await page.getByRole('heading', { name: 'Nuevo nombre QA' }).waitFor();
    await page.locator('[data-action="delete-account"]').click();
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
    await page.getByRole('heading', { name: 'Nuevo nombre QA' }).waitFor();
    await overflow('profile');
    assert.deepEqual(missing, [], 'Missing assets');
    assert.deepEqual(errors, [], 'Browser errors');
    console.log('PASS desktop/mobile rendering, filters, modal cancellation, spinning, registration, profile, no false share progress');
    console.log(`Screenshots: ${output}`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
