const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium, request } = require('playwright');
const base = process.env.CHAPITOUR_TEST_URL || 'http://127.0.0.1:8792/pruebas/chapitour-premia/';
if (!['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('Only an isolated localhost fixture server is allowed.');
const output = process.env.CHAPITOUR_QA_DIR || '/private/tmp/chapitour-panels-qa';
fs.mkdirSync(output,{recursive:true});
(async()=>{
  const contexts=[];
  async function actor(){
    const http=await request.newContext();contexts.push(http);
    let state=await (await http.get(base+'api.php')).json();
    assert(state.csrf,JSON.stringify(state));
    return {http,get state(){return state;},async call(action,data={},expected=200){
      const response=await http.post(base+'api.php',{headers:{'X-CSRF-Token':state.csrf},data:{action,...data}});
      const body=await response.json();assert.equal(response.status(),expected,`${action}: ${JSON.stringify(body)}`);
      if(response.ok())state=body;return body;
    },async refresh(){state=await(await http.get(base+'api.php')).json();return state;}};
  }
  const admin=await actor();
  assert.equal(admin.state.user,null);assert.equal(admin.state.codes.length,0);assert.equal(admin.state.setup_required,true);
  assert.equal((await admin.http.post(base+'api.php',{data:{action:'save_business'}})).status(),403);
  assert.equal((await admin.http.get(base+'api.php?action=redeem')).status(),405);
  await admin.call('login',{email:'laurazoro@gmail.com',password:'wrong-password'},401);
  await admin.call('login',{email:'laurazoro@gmail.com',password:'Qa-admin-old-456!'});
  assert.equal(admin.state.setup_required,false);assert.equal(admin.state.user.must_change_password,true);
  assert.equal(admin.state.codes.length,0);assert.equal(admin.state.businesses.length,0);
  await admin.call('save_business',{},403);
  await admin.call('change_password',{current_password:'wrong',new_password:'Qa-admin-new-456!',confirm_password:'Qa-admin-new-456!'},422);
  await admin.call('change_password',{current_password:'Qa-admin-old-456!',new_password:'Qa-admin-new-456!',confirm_password:'Qa-admin-new-456!'});
  assert.equal(admin.state.user.must_change_password,false);assert.equal(admin.state.businesses.length,6);assert.equal(admin.state.codes.length,5);
  assert(admin.state.promotions.every(p=>p.publication==='draft'));
  assert.equal(admin.state.campaign.enabled,false);
  assert(!JSON.stringify(admin.state).includes('password_hash'));
  await admin.call('demo_login',{role:'admin'},404);
  console.log('PASS real authentication, CSRF, automatic additive schema, mandatory password change, demo access removed');

  const client=await actor(),other=await actor(),ally=await actor(),garage=await actor();
  await client.call('login',{email:'cliente@example.invalid',password:'Qa-client-456!'});
  await other.call('login',{email:'otro@example.invalid',password:'Qa-client-456!'});
  await ally.call('login',{email:'street@example.invalid',password:'Qa-ally-456!'});
  await garage.call('login',{email:'garage@example.invalid',password:'Qa-ally-456!'});
  assert.equal(client.state.codes.length,4);assert.equal(other.state.codes.length,1);
  assert(ally.state.codes.every(c=>c.business_id==='1'));assert.equal(ally.state.businesses.length,1);
  assert(garage.state.codes.every(c=>c.business_id==='4'));assert(ally.state.promotions.every(p=>p.business_id==='1'));
  assert.equal(client.state.challenges.length,3);assert.equal(client.state.challenges.find(c=>c.type==='compartir').progress,null);assert(client.state.challenges.filter(c=>c.type!=='compartir').every(c=>c.progress===0));
  await client.call('prepare_spin',{},422);await client.call('spin',{token:'anything'},422);
  await client.call('redeem',{code:'QA-ACTIVE',confirm:'QA-ACTIVE'},403);
  await client.call('save_promotion',{},403);await ally.call('save_promotion',{},403);await ally.call('save_business',{},403);
  await ally.call('redeem',{code:'QA-OTHER',confirm:'QA-OTHER'},404);
  await other.call('whatsapp',{code:'QA-ACTIVE'},404);
  const wa=await client.call('whatsapp',{code:'QA-ACTIVE'});
  const msg=new URL(wa.whatsapp_url).searchParams.get('text');
  assert(msg.includes('QA-ACTIVE')&&msg.includes('Negocio QA')&&msg.includes('Oferta fixture QA'));
  assert.equal(client.state.codes.find(c=>c.code==='QA-ACTIVE').status,'Activo');
  await ally.call('redeem',{code:'QA-EXPIRED',confirm:'QA-EXPIRED'},409);
  await ally.call('redeem',{code:'QA-REDEEMED',confirm:'QA-REDEEMED'},409);
  await ally.call('redeem',{code:'QA-ACTIVE',confirm:'wrong'},422);
  await ally.call('redeem',{code:'QA-ACTIVE',confirm:'QA-ACTIVE'});
  await admin.call('redeem',{code:'QA-ACTIVE',confirm:'QA-ACTIVE'},409);
  await client.refresh();assert.equal(client.state.codes.find(c=>c.code==='QA-ACTIVE').status,'Redimido');
  await client.call('whatsapp',{code:'QA-ACTIVE'},409);
  const raced=await Promise.all([admin,ally].map(a=>a.http.post(base+'api.php',{headers:{'X-CSRF-Token':a.state.csrf},data:{action:'redeem',code:'QA-RACE',confirm:'QA-RACE'}})));
  assert.deepEqual(raced.map(r=>r.status()).sort(),[200,409]);
  await admin.refresh();await ally.refresh();
  await admin.call('change_status',{code:'QA-EXPIRED',status:'Activo'},404);
  console.log('PASS account and business isolation, WhatsApp without redemption, expired/used rejection, concurrent single redemption');

  const p=admin.state.promotions.find(p=>p.business_id==='1');
  await admin.call('save_promotion',{...p,publication:'approved',whatsapp:'',confirmed:true},422);
  await admin.call('save_promotion',{...p,description:'Oferta editada QA',publication:'draft',whatsapp:'',included:'',hours:'',restrictions:''});
  assert.equal(admin.state.codes.find(c=>c.code==='QA-ACTIVE').description,'Oferta fixture QA, sin valor comercial');
  await admin.call('save_promotion',{...p,publication:'reference'},422);
  await admin.call('save_business',{business_id:'5',name:'',email:'pictogramas-qa@example.invalid',password:'Qa-created-456!'});
  const created=await actor();await created.call('login',{email:'pictogramas-qa@example.invalid',password:'Qa-created-456!'});
  assert.equal(created.state.user.must_change_password,true);
  await created.call('change_password',{current_password:'Qa-created-456!',new_password:'Qa-changed-456!',confirm_password:'Qa-changed-456!'});
  assert.equal(created.state.businesses[0].id,'5');assert.equal(created.state.codes.length,0);
  await admin.call('delete_business',{id:'5',confirm:'wrong'},422);
  await admin.call('delete_business',{id:'5',confirm:'5'});
  await created.refresh();assert.equal(created.state.user,null,'Deleting an ally revokes its other sessions');
  await created.call('login',{email:'pictogramas-qa@example.invalid',password:'Qa-changed-456!'},401);
  await admin.call('save_business',{name:'Aliado sintético QA',email:'nuevo-qa@example.invalid',password:'Qa-new-456!'});
  const b=admin.state.businesses.find(b=>b.email==='nuevo-qa@example.invalid');
  await admin.call('save_promotion',{business_id:b.id,description:'Oferta sintética QA, no comercial',publication:'approved',whatsapp:'10000000',included:'Servicio QA',hours:'Horario QA',restrictions:'Solo QA',confirmed:true});
  const newPromo=admin.state.promotions.find(p=>p.business_id===b.id);
  assert.equal(newPromo.publication,'approved');
  await admin.call('save_promotion',{business_id:b.id,description:'Duplicada',publication:'draft'},409);
  await admin.call('delete_promotion',{id:newPromo.id,confirm:'wrong'},422);
  await admin.call('delete_promotion',{id:newPromo.id,confirm:newPromo.id});
  assert(!admin.state.promotions.some(p=>p.id===newPromo.id));
  await admin.call('save_promotion',{business_id:b.id,description:'Nuevo borrador QA',publication:'draft'});
  assert.equal(admin.state.promotions.find(p=>p.business_id===b.id).publication,'draft');
  console.log('PASS persistent admin CRUD, existing business access, approval validation, archive and session revocation');

  const fresh=await actor();
  await fresh.call('register',{name:'Duplicada',email:'laurazoro@gmail.com',password:'Qa-new-client-456!',city:''},422);
  await fresh.call('register',{name:'Cliente nuevo QA',email:'nuevo-cliente@example.invalid',password:'Qa-new-client-456!',city:'Bogotá',role:'admin'},422);
  await fresh.call('login',{email:'nuevo-cliente@example.invalid',password:'Qa-new-client-456!'});
  assert.equal(fresh.state.user.role,'client');assert.equal(fresh.state.codes.length,0);
  await fresh.call('profile',{name:'Nombre guardado QA',email:'nuevo-cliente@example.invalid',city:'Bogotá D.C.'});
  const second=await actor();await second.call('login',{email:'nuevo-cliente@example.invalid',password:'Qa-new-client-456!'});
  assert.equal(second.state.user.name,'Nombre guardado QA');assert.equal(second.state.user.city,'Bogotá D.C.');
  assert.equal(second.state.user.id,fresh.state.user.id);
  await fresh.call('delete_account',{confirm:'wrong'},422);
  await fresh.call('delete_account',{confirm:fresh.state.user.id});assert.equal(fresh.state.user,null);
  await second.refresh();assert.equal(second.state.user,null);
  await second.call('login',{email:'nuevo-cliente@example.invalid',password:'Qa-new-client-456!'},401);
  console.log('PASS manual registration disabled, existing login without role escalation, cross-browser persistence, profile, deletion and global session revocation');

  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce'});
    await context.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:async()=>{}});});
    const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const capture=async name=>page.screenshot({path:`${output}/${name}.png`,fullPage:true});
    const overflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    const login=async(email,password)=>{
      await page.goto(base);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).first().click();
      await page.locator('dialog input[name="email"]').fill(email);await page.locator('dialog input[name="password"]').fill(password);
      await page.locator('dialog button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
    };
    await page.goto(base);await page.getByRole('button',{name:'Crear mi cuenta',exact:true}).waitFor();
    assert.equal(await page.locator('[data-action^="demo-"]').count(),0);assert.equal(await page.locator('[data-action="choose-demo"]').count(),0);
    await page.locator('[data-action="preview-wheel"]').click();assert(await page.locator('[data-action="spin"]').isDisabled());await page.keyboard.press('Escape');
    await login('laurazoro@gmail.com','Qa-admin-new-456!');await page.getByRole('heading',{name:'Administración de Chapitour'}).waitFor();
    await capture('admin-desktop');
    await page.locator('[data-action="pending"]').click();await page.locator('#publication-filter').waitFor();
    await page.locator('[data-action="edit-promotion"]').first().click();assert(await page.getByRole('button',{name:'Confirmar promoción'}).isVisible());assert(await page.getByRole('button',{name:'Guardar borrador'}).isVisible());await page.keyboard.press('Escape');
    await page.setViewportSize({width:390,height:844});for(const view of ['aliados','promociones','codigos']){await page.goto(base+'#'+view);await page.locator('.app-shell').waitFor();await overflow();await capture('admin-'+view+'-mobile');}
    await page.locator('[data-action="logout"]').click();await page.getByRole('button',{name:'Crear mi cuenta',exact:true}).waitFor();
    await login('garage@example.invalid','Qa-ally-456!');await page.getByRole('heading',{name:'Panel del aliado'}).waitFor();
    assert.equal(await page.locator('[data-action="new-promotion"]').count(),0);
    await page.locator('[data-action="confirm-redeem"]').first().click();await page.getByRole('button',{name:'Cancelar',exact:true}).click();
    assert.equal(await page.locator('[data-action="confirm-redeem"]').count(),1);
    await overflow();await capture('aliado-mobile');await page.locator('[data-action="logout"]').click();
    await login('cliente@example.invalid','Qa-client-456!');await page.getByRole('heading',{name:'Mis retos del mes'}).waitFor();
    const before=await page.locator('.challenge.purple .progress-label').innerText();await page.locator('[data-action="share"]').click();assert.equal(await page.locator('.challenge.purple .progress-label').innerText(),before);
    assert(!/6\/10|cada 10|cada 8|Ingresar código/.test(await page.locator('.return-card').innerText()));
    await overflow();await capture('cliente-mobile');await page.goto(base+'#perfil');await page.locator('[data-form="profile"]').waitFor();
    await page.locator('input[name="name"]').fill('Nombre desde el panel');await page.getByRole('button',{name:'Guardar cambios'}).click();await page.getByRole('heading',{name:'Nombre desde el panel'}).waitFor();
    await page.reload();await page.getByRole('heading',{name:'Nombre desde el panel'}).waitFor();
    await page.locator('[data-action="delete-account"]').click();await page.getByRole('button',{name:'Cancelar',exact:true}).click();await overflow();
    await page.locator('[data-action="logout"]').click();
    await login('nuevo-qa@example.invalid','Qa-new-456!');await page.getByRole('heading',{name:'Cambia tu contraseña temporal'}).waitFor();
    await page.locator('input[name="current_password"]').fill('Qa-new-456!');await page.locator('input[name="new_password"]').fill('Qa-ui-changed-456!');await page.locator('input[name="confirm_password"]').fill('Qa-ui-changed-456!');
    await overflow();await capture('cambio-password-mobile');await page.getByRole('button',{name:'Guardar nueva contraseña'}).click();await page.getByRole('heading',{name:'Panel del aliado'}).waitFor();
    assert.deepEqual(errors,[]);console.log('PASS desktop/mobile dashboards, real login, mandatory password form, filters, cancellation and persistent profile UI');
  }finally{await browser.close();}
  for(const c of contexts)await c.dispose();
  console.log('Screenshots: '+output);
})().catch(e=>{console.error(e);process.exitCode=1;});
